version: '1.0'
name: rocketchat
services:
  - name: mongo
    type: mongodb
    version: 3.4
    configuration: StandAlone
    ports:
      - 27017
    remoteAccess: false
    deployTo:
      - rocket

  - name: rocketchat
    type: docker
    image: rocket.chat
    version: latest
    ports:
      - 3000
    remoteAccess: false
    env:
      MONGO_URL: "mongodb://{{=service('mongo').getMasterAlias()}}:{{=service('mongo').getMainPort()}}/rocketchat"
      ADMIN_NAME: null
      ADMIN_PASS: null
    comments:
      env:
        ADMIN_NAME: Login for an administrator account
        ADMIN_PASS: Password for an administrator account
    volumes:
      - directory: /app/uploads
    deployTo:
      - rocket

  - name: web
    type: nginx
    version: 1.13
    ports:
      - 80
      - 443
    remoteAccess: true
    serviceFiles:
      - name: rocketchat
    deployTo:
      - rocket

hosts:
  - name: rocket
    requirements:
      cores: 1
      memory: 1
